[package]
name = "crane-socket"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "upnp_server"
path = "examples/upnp/server.rs"

[[bin]]
name = "upnp_client"
path = "examples/upnp/client.rs"

[[bin]]
name = "proxy_server"
path = "examples/proxy/proxy_server.rs"

[[bin]]
name = "sender"
path = "examples/proxy/sender.rs"

[[bin]]
name = "receiver"
path = "examples/proxy/receiver.rs"

[dependencies]
easy-upnp = "0.2.1"
tokio = { version = "1.45.1", features = ["full"] }
tokio-tungstenite = "0.27.0"
external-ip = "6.0.0"
thiserror = "2.0.12"
log = "0.4.27"
env_logger = "0.11.8"
dotenv = "0.15.0"
futures-util = "0.3.31"
stunclient = "0.4.1"
serde = { version = "1.0.219", features = ["derive"] }
base64 = "0.22.1"
futures = "0.3.31"
async-trait = "0.1.88"
rand = "0.9.2"
postcard = { version = "1.1.3", features = ["alloc"] }
igd = "0.12.1"

[dev-dependencies]
criterion = "0.7.0"
